spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_SERVER_HOST}/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_USER_NAME}
    password: ${POSTGRESQL_USER_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

server:
  port: 9000
